### ISSUE TITLE
Project Task List

### ISSUE THREAD

**Issue by CZ-RBelo** [CZ-RBelo/Edx-Bootcamp-Portfolio#1]
### Step 1 - Basics

- [x] Research
- [x] Create the basic Wireframe
- [x] Define the Elements

### Step 2 - Navigation Bar

- [x] Add Navigation Bar
- [x] Add Logo / Brand 
- [x] Add links / Menu

### Step 3 - Bio

- [x] Add Bio Element / Background image
- [x] Add Bio Paragraph
- [ ] Add Bio Image

### Step 4 - About Me

- [x] Add About Me Element
- [x] Add About Me Paragraph

### Step 5 - Work

- [x] Define the work Element

> **It is important to define how the element will behave when adding new projects.**

- [x] Add projects

### Step 6 - Contact Me / Footer

- [x] Add Contact Me / Footer Element
- [x] Add links to each contact

### Step 7 - Submit the Project

- [x] Submit

> **Deadline: 12/01/2022 23:59.**
